### ISSUE TITLE
Prevent styles from leaking to other elements

### ISSUE THREAD

**Issue by EmNudge** [kdheepak/remark-svgbob#1]
Following up from [this issue](https://github.com/ratatui-org/ratatui-website/issues/506) and [PR](https://github.com/ratatui-org/ratatui-website/pull/509) around ratatui's website, it seems styles from SVGBob are leaking into other elements.

# Issue Source

The style contains 
```css
line, path, circle, rect, polygon{stroke:black;stroke-width:2;stroke-opacity:1;fill-opacity:1;stroke-linecap:round;stroke-linejoin:miter;}
```
Which creates a stroke around all SVG elements on the page. This leaked into ratatui's header as
![image](https://github.com/kdheepak/remark-svgbob/assets/24513691/c2f7fc73-5ffd-4356-bed9-fb7ece5874bb)

# Possible Fix

If we give the `span` element a custom class name ("svgbob-wasm" or something), we can modify the styles to use this class as a scope. 

This would require bundling a DOM parser library, however.

# Best Fix - Fork SVGBob WASM

This package depends on [SVGBob-WASM](https://github.com/agoose77/svgbob-wasm) which hasn't seen an update in 2 years. In comparison, the actual [SVGBob](https://github.com/ivanceras/svgbob) repo was last updated a week ago. It has already fixed this issue a long time ago. 

If we fork or just recreate the package within this repo, we can get this fix for free.
